--AO3 variables
SIDE_WIT,SIDE_DEF,SIDE_PRO,SIDE_JUD,SIDE_HLD,SIDE_HLP = 0,1,2,3,4,5

--AO2 variables
COLOR_WHITE,COLOR_GREEN,COLOR_RED,COLOR_ORANGE,COLOR_BLUE,COLOR_YELLOW,COLOR_RAINBOW,COLOR_PINK,COLOR_CYAN,COLOR_GREY = 0,1,2,3,4,5,6,7,8,9